const CATALOG = [
    {
        id: 'el1',
        name: 'Голень  говядины',
        img: 'img/card/01.jpeg',
        description: 'Описание мраморной говядины, состоящее из нескольких преложений. Можно наполнить. ',
        price: 950,
        currency: '₽',
        price_separator: '/',
        price_units: 'кг',
        per_text: 'За',
        per_item: '500',
        per_units: 'гр.',
        rating: 5,
    },
    {
        id: 'el2',
        name: 'Мясо по французки',
        img: 'img/card/01.jpeg',
        description: 'Описание мраморной говядины, состоящее из нескольких преложений. Можно наполнить. ',
        price: 300,
        currency: '₽',
        price_separator: '/',
        price_units: 'кг',
        per_text: 'За',
        per_item: '500',
        per_units: 'гр.',
        rating: 2,
    },
    {
        id: 'el3',
        name: 'Мясо классическое',
        img: 'img/card/01.jpeg',
        description: 'Описание мраморной говядины, состоящее из нескольких преложений. Можно наполнить. ',
        price: 1050,
        currency: '₽',
        price_separator: '/',
        price_units: 'кг',
        per_text: 'За',
        per_item: '500',
        per_units: 'гр.',
        rating: 5,
    },
    {
        id: 'el4',
        name: 'Бургерное мясо',
        img: 'img/card/01.jpeg',
        description: 'Описание мраморной говядины, состоящее из нескольких преложений. Можно наполнить. ',
        price: 300,
        currency: '₽',
        price_separator: '/',
        price_units: 'кг',
        per_text: 'За',
        per_item: '500',
        per_units: 'гр.',
        rating: 3,
    },
    {
        id: 'el5',
        name: 'Мясо для бутербродов',
        img: 'img/card/01.jpeg',
        description: 'Описание мраморной говядины, состоящее из нескольких преложений. Можно наполнить. ',
        price: 200,
        currency: '₽',
        price_separator: '/',
        price_units: 'кг',
        per_text: 'За',
        per_item: '500',
        per_units: 'гр.',
        rating: 4,
    },
]